name: Build and Push Docker Images

on:
  push:
    paths:
      - 'bakefile.json'
      - '**/docker-build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push Docker images
        run: |
          docker buildx bake -f bakefiles/bakefile.json --push base
          docker buildx bake -f bakefiles/bakefile.json --push dev
          docker buildx bake -f bakefiles/bakefile.json --push prod
