name: Docker Bake

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
    paths:
      - 'docker/**'
      - 'docker-bake.hcl'
      - '.github/workflows/docker-build.yml'
  workflow_dispatch:

jobs:
  bake:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Resolve bake version
        id: bakevars
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            version="${GITHUB_REF_NAME#v}"
          else
            version="${GITHUB_SHA::7}"
          fi
          echo "version=${version}" >> "$GITHUB_OUTPUT"

      - name: Docker Bake
        uses: docker/bake-action@v5
        with:
          files: docker-bake.hcl
          push: true
          set: |
            *.VERSION=${{ steps.bakevars.outputs.version }}
            *.IMAGE_REPOSITORY=mattocci/afec-bayes
            *.IMAGE_REGISTRY=docker.io

